### PR TITLE
Integrate the Dropbox's zxcvbn library and enforce a minimum password entropy

### PR DESCRIPTION
**Pull request by zah**

### CODE REVIEW

**Comment by arnetheduck** [comment]
Hm, because of dependencies like this, and other stuff related to deposit management only, I think it might be prudent to move the code to a separate binary - this separate binary could for example follow the upstream deposit tool CLI arguments to make it more easy and standard to use

**Comment by cheatfate** [comment]
@zah its not that complex to calculate password's entropy, you don't need to embed external dependency for such simple formula.
https://generatepasswords.org/how-to-calculate-entropy/

**Comment by cheatfate** [comment]
On first look this library supports only ASCII character set, but we going to accept UTF-8 encoded passwords...

**Comment by zah** [comment]
This goes beyond the simple entropy calculation. It's a nice library and a rather small dependency (a single C file)

https://dropbox.tech/security/zxcvbn-realistic-password-strength-estimation
https://github.com/dropbox/zxcvbn

I'm not sure the code needs updating when the inputs are normalized, but I'll think about it more carefully.

**Comment by cheatfate** [comment]
Unicode normalization do not converts everything to ASCII, emojis for example are not going to be normalized, and so this library become useless when password is full of emoji symbols.

**Comment by cheatfate** [comment]
Also its not a simple C file library because it holds pretty big dictionary https://raw.githubusercontent.com/status-im/nim-zxcvbn/master/zxcvbn/C/dict-src.h

**Comment by mratsim** [comment]
As it's crypto-related, please deactivate LTO: https://github.com/status-im/nimbus-eth2/blob/76053142f171ae293c7f4d2bca83cfc22cde52f8/config.nims#L111-L139

It's also not in the hot paths so LTO is not interesting for this while compilation speed is.

**Comment by zah** [comment]
I've added some [UTF-8 test cases](https://github.com/status-im/nim-zxcvbn/commit/ea6de3427d532a77eb83b63f431d5ddb850d5a17) and created an issue that will track further improvements here:
https://github.com/status-im/nim-zxcvbn/issues/1

It shouldn't be too difficult to modify the source code of the library to iterate over runes instead of characters and we can address when we have some time to invest into the problem in the future. At the moment, the library provides pretty good strength estimation for latin alphabet passwords, which are a popular choice for people from all cultures.

**Pull request merged**
