### PR TITLE
use Zinken-compatible message IDs

### PR DESCRIPTION
**Pull request by tersec**
Logtrace needs the "Attestation received" log message to pair with "Attestation sent", and thus either one needs to run in TRACE for that (overkill, usually, especially on the libp2p message side, but even in nbc) or that message needs to show up in DEBUG.

### CODE REVIEW

**Comment by mratsim** [comment]
Pending upstream merge https://github.com/ethereum/eth2.0-specs/pull/2089 cc @djrtwo

**Comment by djrtwo** [comment]
note, this is going into v1.0-candidate release.
I suggest keeping the 32-byte hashes on zinken

**Comment by tersec** [comment]
The base64 version which https://github.com/ethereum/eth2.0-specs/blob/v0.12.2/specs/phase0/p2p-interface.md#topics-and-messages specifies (`message-id: base64(SHA256(message.data))`) and uses 43+ bytes, or the actual-32-bytes version `SHA256(message.data)`?

**Comment by tersec** [comment]
v1.0.0-rc.0 uses a slightly different construction and the logtrace part already went in via a separate PR.

**Pull request closed without merging**
