### PR TITLE
graceful exit on SIGTERM

### PR DESCRIPTION
**Pull request by stefantalpalaru**
Much easier than convincing all users to change the default signal in their service definition file to SIGINT.

### CODE REVIEW

**Review by kdeme — APPROVED** [review]
PR should no longer be made against `devel` now I guess?

**Comment by stefantalpalaru** [comment]
> PR should no longer be made against devel now I guess?

We shouldn't guess about something as important as this. We need proper guidelines - in writing, if we're reinventing some Git workflow we're not familiar with.

**Comment by kdeme** [comment]
> We shouldn't guess about something as important as this. We need proper guidelines - in writing, if we're reinventing some Git workflow we're not familiar with.

Right, agree. (I was guessing as I still saw PRs being merged into devel, but `unstable` exists too)

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/commits/devel has had a few more commits than https://github.com/status-im/nimbus-eth2/commits/unstable

So I'll merge this, and if people want to get `unstable` to being a preferred target, that's fine, but at this point, applying this to `unstable` would cause it to diverge from `devel` in a way that'd just need merging later.

**Pull request merged**
