### PR TITLE
remove async from sub/unsub

### PR DESCRIPTION
**Pull request by sinkingsugar**
Requires https://github.com/status-im/nim-libp2p/pull/490

### CODE REVIEW

**Comment by arnetheduck** [comment]
fails in jenkins job need attention

**Comment by tersec** [comment]
Without "fix unsubscribe wrong key (missed _snappy)", this could go in whenever.

**Comment by sinkingsugar** [comment]
> Without "fix unsubscribe wrong key (missed _snappy)", this could go in whenever, once it passes CI.

but we need that bit to fix broken subs, not sure I understand.

**Comment by tersec** [comment]
> > Without "fix unsubscribe wrong key (missed _snappy)", this could go in whenever, once it passes CI.
> 
> but we need that bit to fix broken subs, not sure I understand.

Fixing unsubs right now exposes other bugs. Another approach is to fix it, but disabling unsubscribing, pending making unsubscribing work with everything else.

The async -> sync transformation itself is fine. It won't fix the sub/unsub stuff in eth2_network, sure, but it shouldn't harm anything either by uncovering other bugs.

**Comment by sinkingsugar** [comment]
> > > Without "fix unsubscribe wrong key (missed _snappy)", this could go in whenever, once it passes CI.
> > 
> > 
> > but we need that bit to fix broken subs, not sure I understand.
> 
> Fixing unsubs right now exposes other bugs. Another approach is to fix it, but disabling unsubscribing, pending making unsubscribing work with everything else.
> 
> The async -> sync transformation itself is fine. It won't fix the sub/unsub stuff in eth2_network, sure, but it shouldn't harm anything either by uncovering other bugs.

ah as in the lesser of two evil, I see. we would still slowly leak and have high traffic tho indeed, less futures tho.

**Comment by tersec** [comment]
With https://github.com/status-im/nimbus-eth2/pull/2201 merged, the PR (when it passes CI) should be fine in its entirety, including its unsub fix.

**Review by tersec — APPROVED** [review]

**Comment by sinkingsugar** [comment]
Works with `USE_VC=0`

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/pull/2205 seems to work.

**Pull request merged**
