### PR TITLE
bump nim-libbacktrace (take two)

### PR DESCRIPTION
**Pull request by stefantalpalaru**
so stack traces work with LTO

### CODE REVIEW

**Comment by tersec** [comment]
Does it break the finalization CI this time?

**Comment by stefantalpalaru** [comment]
> Does it break the finalization CI this time?

No, we finally managed to update CMake on macOS Jenkins hosts: https://github.com/status-im/infra-ci/issues/27

**Comment by mratsim** [comment]
The PRs doesn't break but the branch does? https://ci.status.im/blue/organizations/jenkins/nimbus%2Fnim-beacon-chain%2Fmultibranch/detail/bumplibb/3/pipeline/82#step-83-log-155

Cache issue?

image

**Comment by stefantalpalaru** [comment]
> Cache issue?

Maybe  a matter of multiple CI jobs on the same Jenkins host. The passing job ran on linux-05 and macos-02, while the failing one ran on linux-03 and macos-01.

Or just a flaky test randomly failing. Hard to say. The important thing is that this PR is not to blame.

**Comment by tersec** [comment]
`continuous-integration/jenkins/branch` is still pointing to `nim-beacon-chain`.

**Comment by stefantalpalaru** [comment]
Rebased on "devel".

**Pull request merged**
